import 'package:portfolio/env.dart';

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.webApiKey,
    appId: '1:995982130208:web:19545962ea64109bb59045',
    messagingSenderId: '995982130208',
    projectId: 'jordan-szymczyk',
    authDomain: 'jordan-szymczyk.firebaseapp.com',
    storageBucket: 'jordan-szymczyk.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: '1:995982130208:android:4f26e2e0059e99e1b59045',
    messagingSenderId: '995982130208',
    projectId: 'jordan-szymczyk',
    storageBucket: 'jordan-szymczyk.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: '1:995982130208:ios:7f023479a497ba18b59045',
    messagingSenderId: '995982130208',
    projectId: 'jordan-szymczyk',
    storageBucket: 'jordan-szymczyk.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
